name: Copr Build for CI

inputs:
  copr-user:
    description: The Copr user to build packages under
    required: true
  overlay:
    description: The rpm-gitoverlay overlay name to build (default is dnf-ci)
    default: dnf-ci
  chroot:
    description: The chroot to build for, defaults to the same Fedora that is the Dockerfile's default
    default: ""

outputs:
  package-urls:
    description: The URLs of built RPM packages
    value: ${{steps.copr-build.outputs.package-urls}}

runs:
  using: "composite"
  steps:
    - name: Rebase the pull request on target branch
      shell: bash
      run: |
        REPO_NAME="${{github.event.repository.name}}"
        # if the triggering repo is ci-dnf-stack, the git we are rebasing is in the current directory
        # otherwise, it's cloned into the gits directory for rpm-overlay to build from
        if [ ${REPO_NAME} != "ci-dnf-stack" ]; then
          cd gits/${REPO_NAME}
        else
          # Fix for: https://github.com/actions/checkout/issues/766 (git CVE-2022-24765)
          # This is only needed when running from ci-dnf-stack repo because only then we run in ./ (we do not cd into gits/${REPO_NAME}),
          # this is problematic because the working directory is owned by the github actions runner user not our container user and git
          # doesn't allow that since the mentioned CVE.
          # We have to explicitly state it is a safe directory or create our own subdirectory.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
        fi

        git config user.name github-actions
        git config user.email github-actions@github.com
        echo "Rebasing \"`git log --oneline -1`\" on ${{github.event.pull_request.base.ref}}: \"`git log --oneline -1 origin/${{github.event.pull_request.base.ref}}`\""
        git rebase origin/${{github.event.pull_request.base.ref}}

    - name: Build packages in Copr
      id: copr-build
      shell: bash
      run: |
        PROJECT_NAME="CI-${{github.event.repository.name}}-pr${{github.event.pull_request.number}}"

        if [ -n "${{inputs.chroot}}" ]; then
          CHROOT="${{inputs.chroot}}"
        else
          CHROOT="fedora-$(grep "ARG BASE=" Dockerfile | cut -d':' -f2)-x86_64"
        fi

        # if there's a git already cloned in the `gits` directory, rpm-gitoverlay will use it
        rpm-gitoverlay -o rpmlist --gitdir=gits build-overlay -s "overlays/${{inputs.overlay}}" rpm copr --owner="${{inputs.copr-user}}" --project="$PROJECT_NAME" --additional-repos="copr://rpmsoftwaremanagement/dnf-nightly copr://rpmsoftwaremanagement/dnf5-unstable" --chroots="$CHROOT" --delete-project-after-days=7

        # delete the Copr secret just to be on the safe(er) side when running potentially untrusted PR code (albeit in a container, which should be secure)
        rm -rf "$HOME/.config/copr"

        # convert newlines to spaces (output variable assignment below doesn't support newlines)
        PACKAGE_URLS="$(tr '\n' ' ' < rpmlist)"
        echo "package-urls=$PACKAGE_URLS" >> $GITHUB_OUTPUT
